### ISSUE TITLE
Ships too infrequent late in game

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#100]
I seem to have lost all my ships. In the early game, I was constantly getting mobbed by pirates, so that wasn't an issue. Now, I can never get a ship! I have been searching for one along coastlines for nearly 20k moves, but nothing. I've sealed 4 dungeons and am 7-parts avatar.

**Comment by cambragol** [comment]
I toned down the pirate spawns, because Beta testers were noticing a lot of them.

This will be a tough one to solve...either an area of increased pirate spawns, or a way to buy ships?

How about....a dragon?

**Comment by cambragol** [comment]
It would be easy to code in a Ship Store...but the amount of code it would take is ...insurmountable.

**Comment by Fenyx4** [comment]
I was wandering around in a boat and only nixies, seahorses and whirlpools were spawning.
Since there were so many whirlpools I ended up sinking.

I burned through 200 food trying to get a boat before finding that I still had one parked at Skara Brae. :(

**Comment by MrKnitster** [comment]
Yes, only nixies, seahorses and whirlpools for me as well. Definitely need ship spawns in late game. I think all my parked ships were downed by whirlpools, and now I cannot get to any of the islands (except by laborious blinking, which does not work for the more distant locations).

Of course, a dragon would be fine!

**Comment by cambragol** [comment]
Hmm..the chance of a twister, serpent or whirlpool is all equal to that of a pirate. You are seeing those three, correct?  Nixies, seashorses and squids should be appearing twice as frequently.

**Comment by MrKnitster** [comment]
I'm only seeing seahorses (lots), whirlpools (lots), and nixies (rare).

**Comment by cambragol** [comment]
Dang. This is tough, because it could be a limitation of how the random numbers are generated. It really should be a random distribution of this:

    /*seahorse*/
    /*nixie*/
    /*nixie*/
    /*squid*/
    /*squid*/
    /*serpent*/
    /*seahorse*/
    /*pirate*/
    /*whirlpool*/
    /*twister*/

To only end up with what you are seeing is an error in the randomness of the random number. I don't thing I can fix that though.
I'll try doubling the list and the size of the random number, to try and keep the same distribution.

If that doesn't work I will have to just double the instances of pirates.

**Comment by cambragol** [comment]
Okay, that made it worse

I am seeing the same thing. Seahorses and NIxies, nothing else.

**Comment by cambragol** [comment]
I think I have it working, but the solution is imperfect. I may have to revisit this and all randomness for spawning.

**Comment by Fenyx4** [comment]
I do get the very very rare twister too.
Odd that the random number generator appears to be weighting the outsides of the array

Would you like me to dig into the coffee of the base game to try to figure out what it is doing? I dunno how much it has been modified in TotT.

**Comment by cambragol** [comment]
zero modification. Just using the same setup as U4:  [U4_RND1(U4_RND1(9))]

A nested double call to U4_RND1.

By all means take a look. I haven't really, as I am not sure I grasp how the random numbers is working, and just assumed the default would work(as it did in default 4)

**Comment by cambragol** [comment]
I used the nested double random call because that is what was used in the original spawning algorithm. I had assumed that it gave some kind of weighting to the lower level monsters. 

However, I just tried using a single call to U4_RND4, rather than U4_RND1, and I am seeing much, much better distributions. In fact, I realized now that I haven't seen certain monsters for awhile when testing (headless, lich, rogues), But now, suddenly I am seeing them.

Will keep this on for a bit and see what I am seeing.

**Comment by Fenyx4** [comment]
U4_RND1 uses & instead of %. Unless you give it a power of 2 minus 1 (i.e. 3, 7, 15) it will behave oddly. But & is much faster than % which is probably why it is used. (Source: https://stackoverflow.com/questions/18674977/using-bitwise-instead-of-modulus-operator-to-randomly-sample-integers-from-a-r)

For example I think if you pass in 7 to U4_RND1 you could get 0-7 but if you pass in 9 you could only get 0,1,8,9.

So if you are changing the spawning to have values other than powers of 2 minus 1 you should probably switch it to U4_RND4.

Although the base game would have gotten that oddness from the second call to U4_RND1... I dunno if that odd behaviour is what RG wanted... So, maybe do U4_RND1(U4_RND4(9))? But if you want it be more predictable going with U4_RND4(U4_RND4(9)) would probably be best. 

Or if you KNOW you aren't passing in 0 then you could speed it up a bit more with U4_RND4(U4_RND3(9)).

**Comment by cambragol** [comment]
Well, that is very useful chunk of info! I just never had a need to look into the details of how it was working, as it was 'kind of' working. 

I notice now in the code that the default seems to be using 3s, 7s, 15s, etc with U4_RND1.
There are a couple of more instances where I used U4_RND1 without much thought, but considering this, I should go over those and maybe switch to U4_RND4 or go to a power of 2 minus 1.

Thanks!

**Comment by cambragol** [comment]
Well, I have switched over to usuing U4_RND4 in most cases, and I am now seeing spawns accurately reflected in the world. I am not going to go with a double call, to weight it at the lower end, but will just build the weighting into the lists themselves. 

So, next Beta should see some new/more accurate spawning.

And...we should be seeing ships again, no matter even with reduced spawns from dungeon closures and achieving avatarhood. Though, they will still be less frequent. We'll see how tough that makes it.

**Comment by Fenyx4** [comment]
Adding this here because I am guessing it is related to the random number issues. (Especially since I checked and it uses U4_RND1 in the base game)

I am on L7 of Spider Cave and holed up and camped 10 times. Got ambushed every time.

**Comment by cambragol** [comment]
I update the random numbers for camping too already. Next update will have them.

**Comment by MrKnitster** [comment]
Well, ships are back. Unfortunately, just like monsters, they disappear after you defeat them. I don't mean blasting the ship with a cannon; I mean after you attack and defeat all of the pirates, you leave the combat screen and the ship is gone.

**Comment by cambragol** [comment]
Ahhh..fixing the bug which caused post pirate attack Hole and Camp to be beside a ship, caused this bug. We just didn't notice until now. Will get on fixing asap.

**Comment by cambragol** [comment]
Here is a hotfix for that. I feel bad after all the time waiting for a ship!

[AVATAR.EXE.zip](https://github.com/cambragol/advent-of-the-trinity/files/5644054/AVATAR.EXE.zip)

**Comment by cambragol** [comment]
> Adding this here because I am guessing it is related to the random number issues. (Especially since I checked and it uses U4_RND1 in the base game)
> 
> I am on L7 of Spider Cave and holed up and camped 10 times. Got ambushed every time.

See my hotfix above.

**Comment by MrKnitster** [comment]
Ha! No worries. Thanks for jumping on the fix so quickly.

**Comment by MrKnitster** [comment]
Not seeing ships at all now. Every other water monster seams to be spawning, including whirlpools. No ships.

**Comment by cambragol** [comment]
Did you get the edited, i.e. second hotfix above? I don't think that matters, as it only addressed the ambushes thing.However, I just tested and got two pirate ships within a few minutes.

If this continues, please attach your save files and I will test

**Comment by cambragol** [comment]
I think spawing has been fixed, or is at least spawning correctly from lists now.

However, the problem of late game pirates being missing may remain. Once the dungeons are closed, and avatarship is reached, the spawns will be waaaay down.  Which will make getting a ship very difficult.  

I can see three choices:

Make a ship seller - fun, but a feat of impossibility with the limited code space
Make pirate spawn points - possible
Give the ocean special spawn rules, exempt from the cooldown of closing dungeons and gaining avatarhood.

**Comment by cambragol** [comment]
Well, I have a shipwright in game! 

Crazy coding to get it done in net 2 lines of code. But, I spent 2 lines of code, which means something might have to be cut to include this. Currently I have turned off spawning from caves, mines and dungeons entrances to make this gif.

![shipshop](https://user-images.githubusercontent.com/5019739/101233719-20cf1480-36fd-11eb-961f-741ec9849fb0.gif)

**Comment by Fenyx4** [comment]
Wha-bu... How did you do that in 2 lines?! You are a miracle worker.

**Comment by cambragol** [comment]
Boohoohahah!

Piggybacked on the Horse shop, Balloon generation code, and a global or two.

**Comment by cambragol** [comment]
I want feedback on whether it is critical/good to add though. I changed the first floor of Minoc, and we will have to lose a small feature elsewhere. I am thinking the safe zone around cities, as I don't think it is that effective, since it only works when leaving, but monsters that followed you to a city will still be respawned by the OutMonst.sav

**Comment by cambragol** [comment]
I fixed the code a little, and can now add a couple of shipwrights at no code cost. 

Currently I have one in Minoc. Other possibilities would be Britain or castle Britannia, and Jhelom, to foreshadow the shipwrights which appear in Ultima V.

I'm just wondering if it is too much to add 3? Hmm.

**Comment by MrKnitster** [comment]
That is fantastic! Great job squeezing that in. I think the game has a really good transition-between-U4-and-U5 vibe, so I would advocate for just one shipwright. Minoc seems perfect, with its harbor and all. I can't wait to see it in game!

**Comment by cambragol** [comment]
I like the look of the shipwright in Minoc, but...I really have tried not to alter the first levels of all towns. Only tiny alterations to fit ladders, or add windows so far.

Jhelom would be a good target, as I could fit a 2nd floor shipwright's office above the healer maybe. Then the first level would remain sacrosanct.

**Comment by cambragol** [comment]
Also, Minoc's harbor is shallow and 'locked'. I'd have to alter the map.

No need in Jhelom.

However, the 'oldest' shipwright in Ultima V was based in Britanny...so around there is a good target for a mid-way between Ultima IV and V vibe.

**Comment by MrKnitster** [comment]
In that case, I think you should probably go with Jhelom or Britain. Of those two, Britain probably makes the most sense; it is closest to the site of the first shipwright in U5, LB's castle is right there, and it is very central.

**Comment by Fenyx4** [comment]
I had a random thought today... Could you have the Minoc map change partway through the game?

Then it could start with no shipwright and have one built as time passes? Perhaps when action count is above 60,000 or when they have all the stones.

Positive:
It would start with minimal modification to the town map. But then show time passing.

Negative:
People may not notice that it was added.

**Comment by cambragol** [comment]
ohh...
quite possible. I actually already have the code for that somewhere already. I had planned on having the entire map change according to the state of the game, as well as each town go through 2-3 phases of change.

So it is possible. Very simple as you can guess.

But...is it too much for such a small consideration? I like it, but if I did that it would seem warranted to have a few other things change as well.

**Comment by cambragol** [comment]
Maybe I should add, my original intention was to reflect changes in towns based on the players overall 'karma' rating. So if it got lower, the towns would be come damaged, rundown, and the people would become less 'virtuous'. If the karma went up, the towns would become clean and pristine again, and the people would be polite and virtuous.

I scrapped it because it would have at least tripled the work I would have to do on dialogues.

**Comment by cambragol** [comment]
Closing this, as it is doubly addressed, with the new spawn balance, and the availability of shipwrights to buy ships.
