### ISSUE TITLE
Moongates in the Underdeep

### ISSUE THREAD

**Issue by Fenyx4** [cambragol/advent-of-the-trinity#115]
![image](https://user-images.githubusercontent.com/2976266/101272145-2ce3c200-374f-11eb-8250-85dd19bf8f03.png)

![image](https://user-images.githubusercontent.com/2976266/101272151-39681a80-374f-11eb-8315-156720401777.png)

It is always open and seems to only take me to the shrine of Spirituality.

**Comment by cambragol** [comment]
hm..I just checked that, and I am not seeing that.

Are you using the latest beta with the hotfix from #100 ?

I will check around more, as I thought I had turned off the moongates with the moons, but maybe I didn't.

**Comment by cambragol** [comment]
The moons at the top of the screen are missing, so that means moongates are turned off. 

This almost has me stumped. But I can only imagine that you must have entered the underworld while the moons were set to full, so the destination is the shrine of spirituality. The animation was turned off, but the moons were not erased, so the moongate was frozen in an open state.

Which means simply stopping the animations of the moons is not sufficient. I will have to find a way to turn them off, or bury them in stone.

Very good catch on this bug, as many of the moongates are buried already. A very lucky catch I think.

**Comment by cambragol** [comment]
Fixing this in code will be too costly.  I will bury the moongates.

**Comment by cambragol** [comment]
Fixed.
