### ISSUE TITLE
Ring

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#148]
I'll cloak this just in case:

<details> 
  <summary>Spoiler</summary>
  The ring obviously protects you from poison in swamps. Very cool; sort of a precursor to the beloved swamp boots of U5 and beyond.

However, to get the benefit, you have to [U]se the ring, and the effect is only temporary. I find myself in swamps (especially in the Underdeep) reflexively [U]sing the ring every few paces to make sure it doesn't stop. Reminds me of the Silver Horn. Ugh. Any way to make protection automatic once the item is in inventory? Or is that too easy for the player? Unlike the horn, wearing an item does not seem like it should be a temporary effect...
</details>

**Comment by cambragol** [comment]
<details> 
  <summary>Spoiler</summary>
  Actually, I originally had it working the way you describe, i.e. 'always on', because I didn't have space to make it 'useable'. Once I got some code space I made the the ring function through 'use' to make it consistent with other items in the game.
I could reverse it to the old way if that is more enjoyable. An alternative would be to have it usable, but it lasts longer.
</details>

**Comment by cambragol** [comment]
This could still be switched to 'always on'. However, the Staff of the Avatar will augment the duration of the ring effect when used in conjunction, making keeping it a to be 'used' item makes more sense. 

Unless Fenyx4 chimes in with strong agreement for making it always on, we'll just keep it as is.

**Comment by Fenyx4** [comment]
As is works for me.
