### ISSUE TITLE
Armor in Tree in Jhelom (SAV file behaviour)

### ISSUE THREAD

**Issue by TheVaxen** [cambragol/advent-of-the-trinity#32]
After speaking to the woman in the inn about her life of leisure, and asking her about the window, she mentions the shiny armor in the tree below. I've found it in the previous version but can't find it now with this new version. Has it been moved from the area below the inn's window?

**Comment by cambragol** [comment]
If you are using the same save file, then it won't be there. You can only ever find any of these items once.

If it is a fresh game, then that is a bug. Or a bugged .sav file.

**Comment by TheVaxen** [comment]
Interesting, I just hit up the blacksmith in Trinsic and the item appears to be missing as well. I copied the new files from the ZIP into my existing directory, and started a new game. Theoretically everything should have reset, right?

**Comment by cambragol** [comment]
Yes, if the save files were overwritten, everything should be reset. Maybe, somehow, one of your save files was not overwritten? The key one would be items.sav

**Comment by cambragol** [comment]
Try just emptying your game folder completely, then adding the new beta files.

**Comment by MrKnitster** [comment]
Sorry; was away all weekend. Just downloaded newest beta. I started a new game and bee-lined it to Jhelom. Searched trees and found plate armor.

**Comment by TheVaxen** [comment]
Starting a new game should in theory generate a new set of SAV files though right? I wonder if this was a behaviour of the original DOS game?

**Comment by MrKnitster** [comment]
Must have generated new sav file for me, as the armor was there...

**Comment by TheVaxen** [comment]
I just deleted the SAV files in the main directory and started a fresh game... and the armor is still not there. Puzzling.

**Comment by TheVaxen** [comment]
So just to clarify, I'm using the GOG version of U4, and set it up originally by just overwriting all the files in the directory with the AOTT files. Any additional files were left in situ in the directory. When I installed the newer version of AOTT, I overwrite the files in that same directory again.

**Comment by TheVaxen** [comment]
Interestingly, the weapon/armor in Trinsic is there now. Will head back to Jhelom to see if it's there. Does it make a difference what class you are?

**Comment by cambragol** [comment]
Class does not matter.

Actually, starting a new save game generates a new player.sav file. But not the other 3 files, as far as I know.

Save games are compatible, but ToTT has an additional save file not present in default: items.sav

This file tracks the various items, gold, keys, weapons that you can find as secondary mini-quests. I believe you guys have hit on a bug, because I am not regenerating that file when a new game is started, so potentially you will not be able to find items when starting new games, unless you copied over the items.sav from a new beta version.

Will look into this now, as it is quite critical. Fortunately this stuff is all handled in Title.exe, where I have lots of coding space available.

**Comment by TheVaxen** [comment]
Does TOTT.zip have the SAV file there? I extracted directly into the directory and overwrote any existing files.

**Comment by cambragol** [comment]
Yes, it is in there, so overwriting resets your game completely.

**Comment by TheVaxen** [comment]
So I deleted all the SAV files from the main directory and the game still booted and ran with an older savegame, which means that it's pulling the SAV files from one of the other directories. When I deleted all of those directories, the game would crash when launching from the main menu, so at least with the GOG version there's something different happening there. It's using the DOSBox emulator for anyone who's curious.

**Comment by TheVaxen** [comment]
Yup, appears to save to the cloud_saves directory. Interestingly if you delete the SAV files from the main directory the game won't work, but it doesn't seem to use those files afterwards based on timestamps.

**Comment by cambragol** [comment]
Okay, the game now properly sets up player.sav and items.sav when starting a new game. Items was overlooked before, so the first init of a new game would have worked, but after that any new game starts would have had the same items already being found as the previous save game. 

So that is fixed now. 

As for other issues. I have the DOSBox emulator version from GOG, but it doesn't have any cloud save directories. So...that is weird.

Still, these are just emulator issues. The game itself is working. Let's just keep in mind that the 4 critical files for your game are: player.sav, monsters.sav, outmonst.sav and items.sav

Keep those to keep your game. Don't overwrite them when getting a new Beta. The ones you want to use must be in the same directory as avatar.exe, i.e. the main directory. 

Anything else doesn't matter, because any third party emulator/handler has to deal with those files, and keep them in that location. I think.

**Comment by cambragol** [comment]
I am closing this now, as the original issue, new games not resetting items, is fixed. New games will have all findable items reset.
