### ISSUE TITLE
Rune of Justice

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#36]
Leader in Yew still reports rune as being located in cell. Searched every square; no rune. I did not expect one there, as you said you moved them all. Is his message a bug, or am I missing something? Incidentally, could not find the rune elsewhere, and no one else seemed to respond to the RUNE keyword.

**Comment by cambragol** [comment]
What does he report exactly?

**Comment by TheVaxen** [comment]
After you answer no to his question about never being guilty he says "seek thee well within the cell, where evil most foul doth justly dwell".

**Comment by cambragol** [comment]
Ah! Is evil most foul just a felon?  Ask the judge further, for more clues.

The original clue from Judge Talfourd is: Then do thy penance in a cell, and with the felon search ye well.

This was a quest modified since the Beta started. I tried to make the clue similar to the default, but the quest is now much bigger/longer. Perhaps my clue is insufficient.

**Comment by cambragol** [comment]
Is this still a bug? Should I change this quest?

**Comment by MrKnitster** [comment]
Not a bug at all! Good work with red herrings, etc. Makes the game seem fresh for old players, while still having continuity. Very good job on that. Sorry I did not follow up. I did find it.

**Comment by cambragol** [comment]
okay, cool. Closing then.
