### ISSUE TITLE
Swamp in Dungeon Rooms

### ISSUE THREAD

**Issue by Fenyx4** [cambragol/advent-of-the-trinity#65]
I am in Dewmire 3rd level center dungeon room and the swamps aren't poisoning me.

Went east and still no poison on swamps.

**Comment by Fenyx4** [comment]
When I get back to the overworld I'll check those swamps.

**Comment by cambragol** [comment]
I turned off swamp poisoning in dungeon rooms. In default U4, swamps in combat was INSTANT poisoning, which was just silly. 

There is still a chance in the wild, and in towns, though lowered.

**Comment by cambragol** [comment]
I wonder whether turning off poisoning is the right choice? Granted, it seems a little unrealistic to get 'poisoned' or come down with a fever when taking a single step in a swamp during combat. However, it adds a strategic element to the battle. 

For me that came down to NEVER stepping foot in a swamp in swamp combat, because of the instant poisoning. So does that really add any strategy? Or would being able to venture out into the swamp ground without fear of poisoning be 'more' strategy? Not sure.

**Comment by cambragol** [comment]
I'm going to close this, because I am convinced we don't need instant 100% poisoning when taking one step on a swamp in a combat map.

**Comment by Fenyx4** [comment]
Sorry missed the earlier comment. I agree instant poison doesn't make sense.
