### ISSUE TITLE
Conversation Capitalization

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#89]
This is incredibly picky. Most conversation lines start with a capital letter. When a line begins with an apostrophe, such as 'tis, the t is not capitalized (the original code must have only applied to the first character, so the t, being the second character, was missed). This is probably original, not the mod, but thought I'd point it out. It happens all over, and I noticed it twice in Trinsic, for instance.

**Comment by cambragol** [comment]
'Tis the season to contemplate this grammar point!

I tweaked some of the dialogue from 'tis to 'Tis, because it was inconsistent thoughout the game. However, I didn't look into the issue deeply, and assumed 'Tis was correct, as the T is the first letter of the first word, the I being replaced with an apostrophe. 

Looking through ddg, it seems this may be a contentious point...
The most common usage I see of it, which is mostly capitalized, is in the phrase 'Tis the season...
