### ISSUE TITLE
Serpent's Hold Typos

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#97]
Okay, final typos for today; sorry for all the posts...

The ankh says: "They still tarry in spectral form, for their sacrifce may yet be in vain." [should read "sacrifice"]

Nothor says: "Swamps are the most dangerous when travelling." [should read "traveling"]

Draxx says: "I am visualising my sword strokes." [should read "visualizing"]

**Comment by cambragol** [comment]
Don't be sorry! This is the first time I couldn't get through everything in one sitting. Nice work!

Fixed the Ankh.

Travelling or traveling works...not sure whether this a British/American English thing, but both are accepted. I think there is another 'travelled' some where in the default...so this I will keep.

Visualising is definitely British/American. I think many default spelling are British, because Lord British  was...er...in England at that time? I've seen both spelling here and there, though graphics are definitely British English (Armour etc.)
